apiVersion: apps/v1
kind: Deployment
metadata:
  name: chemai-discovery
  labels:
    app: chemai-discovery
    version: v2.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chemai-discovery
  template:
    metadata:
      labels:
        app: chemai-discovery
    spec:
      containers:
      - name: chemai-discovery
        image: chemai/discovery:v2.0.0
        ports:
        - containerPort: 8000
        env:
        - name: GPU_ENABLED
          value: "false"
        - name: MAX_WORKERS
          value: "4"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: models-volume
          mountPath: /app/models
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: chemai-data-pvc
      - name: models-volume
        persistentVolumeClaim:
          claimName: chemai-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: chemai-discovery-service
spec:
  selector:
    app: chemai-discovery
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chemai-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chemai-models-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
